import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Navbar from "@/components/Navbar"; // if alias isn't set, use ../components/Navbar

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-CDLBZYY7KW"
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){window.dataLayer.push(arguments);}
            window.gtag = gtag;
            gtag('js', new Date());
            gtag('config', 'G-CDLBZYY7KW');
          `}
        </Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-twilight text-ashWhisper`}>
        <div className="min-h-screen flex flex-col">
          {/* Site-wide nav */}
          <Navbar />

          {/* Page content */}
          <main className="flex-1">{children}</main>

          {/* Powered-by strip (optional) */}
          <div className="bg-ritualInk text-center py-4 text-sm text-neutral-400">
            Built with{" "}
            <a
              href="https://koraintelligence.com"
              target="_blank"
              rel="noreferrer"
              className="underline hover:text-burnishedGold"
            >
              Kora Companions
            </a>{" "}
            · Every conversation becomes a scroll.
          </div>
        </div>
      </body>
    </html>
  );
}